# Generated by Django 4.1.5 on 2023-02-12 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoptube', '0002_product_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quantity',
            new_name='quan',
        ),
    ]
