# Generated by Django 4.1.5 on 2023-02-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoptube', '0003_rename_quantity_orderitem_quan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderitem',
            old_name='quan',
            new_name='quantity',
        ),
    ]
