# Generated by Django 4.1.5 on 2023-02-16 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoptube', '0006_alter_product_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
